name: Generate Snake Animation

on:
  schedule:
    # Executa o workflow a cada 12 horas
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checkout do repositório
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Gera a animação da cobra
      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: WiniciusPichirilo
          # Opções de customização
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark
            dist/ocean.gif?color_snake=orange&color_dots=#bfd6f6,#8dbdff,#64a1f4,#4b91f1,#3c7dd9

      # Deploy para a branch gh-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # (Opcional) Atualiza o README com a imagem gerada
      - name: Update README with Snake Animation
        run: |
          echo "![Snake animation](https://github.com/WiniciusPichirilo/WiniciusPichirilo/blob/output/github-contribution-grid-snake.svg)" >> README.md
